dic = {
    "arse": True,
    "arsehead": True,
    "arsehole": True,
    "ass": True,
    "asshole": True,
    "bastard": True,
    "bitch": True,
    "bloody": True,
    "bollocks": True,
    "brotherfucker": True,
    "bugger": True,
    "bullshit": True,
    "child-fucker": True,
    "Christ on a bike": True,
    "Christ on a cracker": True,
    "cock": True,
    "cocksucker": True,
    "crap": True,
    "cunt": True,
    "damn": True,
    "damn it": True,
    "dick": True,
    "dickhead": True,
    "dyke": True,
    "fatherfucker": True,
    "frigger": True,
    "fuck": True,
    "fucking": True,
    "goddamn": True,
    "godsdamn": True,
    "hell": True,
    "holy shit": True,
    "horseshit": True,
    "in shit": True,
    "Jesus Christ": True,
    "Jesus fuck": True,
    "Jesus H. Christ": True,
    "Jesus Harold Christ": True,
    "Jesus, Mary and Joseph": True,
    "Jesus wept": True,
    "kike": True,
    "motherfucker": True,
    "nigga": True,
    "nigra": True,
    "pigfucker": True,
    "piss": True,
    "prick": True,
    "pussy": True,
    "shit": True,
    "shit ass": True,
    "shite": True,
    "sisterfucker": True,
    "slut": True,
    "son of a whore": True,
    "son of a bitch": True,
    "spastic": True,
    "sweet Jesus": True,
    "turd": True,
    "twat": True,
    "wanker": True,
}

def is_profane(text):
    words = text.split()
    for word in words:
        if word.lower() in dic:
            return True
    return False