import os
import subprocess
# This file will find all test files in the project and run pytest on them.

# DO NOT EDIT THIS FILE
def run_pytest(root_directory):
    for root, dirs, files in os.walk(root_directory):
        for file in files:
            if file.startswith("tests_") and file.endswith(".py"):
                test_file = os.path.join(root, file)
                print(f"Running pytest for: {test_file}")
                subprocess.run(["pytest", test_file])

if __name__ == "__main__":
    root_directory = os.path.abspath(os.path.dirname(__file__))
    run_pytest(root_directory)