version: '3.8'
services:
  ww-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: uvicorn ww-be.main:app --host 0.0.0.0 --port 8000 --reload
